version: "3.8"

services:
  brushnet:
    container_name: brushnet
    image: maximofn/brushnet:1.0.1
    build: .
    runtime: nvidia
    network_mode: "host"
    volumes:
      - ./hub:/root/.cache/huggingface/hub
    tty: true
    stdin_open: true
